#!/bin/bash
filename="*\\\\'\"Best School\"'\\\\*$\\?\\*\\*\\*\\*\\*:)"
echo "Best School" > "$filename"
echo >> "$filename"
echo "File '$filename' created with the text 'Best School' and a new line."
