#!/usr/bin/env bash
#Bash script that Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

#!/bin/bash

# Function to handle SIGTERM signal
term_handler() {
    echo "I hate the kill command"
    cleanup_and_exit
}

# Function to handle SIGINT signal
int_handler() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit_handler() {
    echo "Deleting PID file and terminating script"
    cleanup_and_exit
}

# Function to perform cleanup and exit
cleanup_and_exit() {
    rm /var/run/myscript.pid
    exit 0
}

# Register signal handlers
trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT

# Create PID file
echo $$ > /var/run/myscript.pid

# Display message until PID file is deleted
while [ -f "/var/run/myscript.pid" ]
do
    echo "To infinity and beyond"
    sleep 1
done

# Cleanup and exit when PID file is deleted
cleanup_and_exit
