#!/usr/bin/env bash
"Using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments."

for ((i=1; i<=10; i++))
do
    echo "Best School"
done
