#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

for ((i=1; i<=100; i++))
do
    if ((i % 3 == 0)) && ((i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo $i
    fi
done
