#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

awk '{ count[$1,$9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -rn
