#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

count=0

while [ $count -lt 10 ]
do
    echo "Best School"
    count=$((count + 1))
done
