#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    
    count=$((count + 1))
done
