#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done
