#!/usr/bin/env bash
#using #!/usr/bin/env bash in the shebang line provides more flexibility, portability, and simplicity when running Bash scripts across different systems or environments.

for file in *
do
    if [ -f "$file" ] && [[ "$file" != .* ]]
    then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
