#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to configure the desired mappings
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Display the modified hosts file
cat /etc/hosts
