#!/usr/bin/env bash
#Bash script that configures an Ubuntu server.

# Update the system
sudo apt update
sudo apt upgrade -y

# Configure the hosts file
sudo bash -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

# Restart the networking service
sudo service networking restart

# Verify the changes
ping localhost
ping facebook.com
