#!/usr/bin/env bash
#Bash script that configures an Ubuntu server.

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to configure the desired mappings
sudo bash -c 'echo "127.0.0.2 localhost" > /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

# Flush the DNS cache
sudo systemd-resolve --flush-caches

# Display the modified hosts file
cat /etc/hosts
